### ISSUE TITLE
[debug] Server crashed due to an unknown error

### ISSUE THREAD

**Issue by DitzyIsNothing** [AmyrAhmady/sampvoice#16]
The voice button worked fine before I used GMX, and after I used GMX, when I pressed the B/Voice button, the server suddenly crashed, is it true that sampvoice can't use GMX?

or this error is not from sampvoice?
![image](https://github.com/AmyrAhmady/sampvoice/assets/126363790/83457344-70bc-4b9b-9a81-110444302763)

**Comment by DitzyIT** [comment]
#13I don't understand this problem, and how to fix it, how to comment on it, like what @andreev02 is talking about.

i hope anyone can help this issue.
I don't understand this problem, and how to fix it, how to comment on it, like what @andreev02 is talking about.

i hope anyone can help this issue.

![image](https://github.com/AmyrAhmady/sampvoice/assets/126363790/8b2064e3-aa4c-455c-ba6b-4f185bf01f6a)

**Comment by DitzyIsNothing** [comment]
Okay i found the solution of this issue, i put this script in OnGameModeInit for disconnecting all player when using gmx, and its working.

        ```
for (new i = 0, j = MAX_PLAYERS; i <= j; i++) 
	{
		if (IsPlayerConnected(i))
		{
			OnPlayerDisconnect(i, 1);
		}
	}
```

**Comment by DitzyIsNothing** [comment]
Oke.. i found solution of this issue, i put this script OnGameModeInit for disconnecting all player.

for (new i = 0, j = MAX_PLAYERS; i <= j; i++) 
	{
		if (IsPlayerConnected(i))
		{
			OnPlayerDisconnect(i, 1);
		}
	}
