### ISSUE TITLE
Problem with YSI

### ISSUE THREAD

**Issue by AthallahDzaki** [AmyrAhmady/sampvoice#3]
[Here the problem](https://github.com/pawn-lang/YSI-Includes/issues/595)

**Comment by AthallahDzaki** [comment]
[As Y_Less say](https://discord.com/channels/231799104731217931/231799180127895553/984447246026305606)

**Comment by AmyrAhmady** [comment]
Give me a simple minimal example script that can reproduce this problem

**Comment by AmyrAhmady** [comment]
Also which callback/line reports this error? `error 025: function heading differs from prototype`

**Comment by AthallahDzaki** [comment]
[This Line](https://github.com/AmyrAhmady/sampvoice/blob/b0380be24920d2d54f534bd36d9e2188b3476596/server/sampvoice.inc#L95)

```
#include <sampvoice>
#include <YSI/YSI>

SV_VOID:OnPlayerActivationKeyRelease(playerid, keyid)
{
    if(keyid == 0x42) SendClientMessage(playerid, -1, "OK");
}
```

**Comment by AmyrAhmady** [comment]
It looks like you are using an outdated version of YSI, also are you using open.mp?

**Comment by AthallahDzaki** [comment]
> It looks like you are using an outdated version of YSI, also are you using open.mp?

Currently im not using OMP, but i will try it next time

**Comment by AmyrAhmady** [comment]
This repository is only for open.mp adoption of sampvoice, doesn't work with samp
and I have already fixed caching issues here, which means if you want to get the fix you should move to open.mp, or else wait for original developer do to fix it
