### ISSUE TITLE
 Added pawn.json file

### ISSUE THREAD

**Issue by lucasgama335** [AmyrAhmady/sampvoice#7]
it is not possible to install this version of sampvoice with sampctl, because the pawn.json file is missing, to specify the paths of the .dll and .inc files

<p align="left">
	<img src="https://i.imgur.com/PGE0syn.png">
</p>
Without the .dll file in the plugins folder and without the include.

Original Request ([https://github.com/Southclaws/sampctl/issues/475](https://github.com/Southclaws/sampctl/issues/475))

**Comment by AmyrAhmady** [comment]
Create a pull request for it to add support if you want, I do not use sampctl and I do not know about the specifications.
